name: Deploy Node.js to Azure WebApp
on: [workflow_dispatch, push]
env:
  AZURE_WEBAPP_NAME: node-service-template
  NODE_VERSION: "14.x"
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies and build
        run: |
          npm ci
          npm run build
      - name: Run automated tests
        run: npm test
      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
